version: "3"

services:
  db:
    image: "mariadb"
    container_name: "floor_server_db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "floor"
    volumes:
      - "floor_server_data:/var/lib/mysql"

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: "floor_server_phpmyadmin"
    ports:
      - "8080:80"
    volumes:
      - "/sessions"

  api:
    image: "floor_server_api"
    container_name: "floor_server_api"
    build: .
    environment:
      - PORT
      - FLOOR
    ports:
      - ${PORT}:${PORT}

volumes:
  floor_server_data: ~
